pub const QUOTES: [&str; 52] = [
    "The only way to do great work is to love what you do.",
    "Innovation distinguishes between a leader and a follower.",
    "The best way to predict the future is to invent it.",
    "The only limit to our realization of tomorrow will be our doubts of today.",
    "Success is not final, failure is not fatal: It is the courage to continue that counts.",
    "SEO is not about tricking Google. It's about partnering with Google to provide the best search results for users.",
    "Good SEO is paying attention to all the details that make a website great.",
    "Content is king, but SEO is the queen and she runs the household.",
    "The best place to hide a dead body is page two of Google search results.",
    "SEO is a race, not a sprint. Consistency and patience win.",
    "Marketing is no longer about the stuff you make, but the stories you tell.",
    "Build software as if the person who ends up maintaining it is a violent psychopath who knows where you live.",
    "Good software, like wine, takes time.",
    "If debugging is the process of removing bugs, then programming must be the process of putting them in.",
    "Marketing without data is like driving with your eyes closed.",
    "Content that educates wins over content that sells.",
    "The most successful marketers are those who can tell stories that resonate.",
    "Fail fast, learn faster.",
    "A brand is no longer what we tell the consumer it is—it’s what consumers tell each other it is.",
    "Write code that you would be proud to show in a job interview.",
    "Your marketing plan is worthless if you don’t measure it.",
    "A website without SEO is like a car without fuel.",
    "The best software developers are not those who code the fastest, but those who code the clearest.",
    "Good marketing makes the company look smart. Great marketing makes the customer feel smart.",
    "Refactor early, refactor often.",
    "Testing is not optional—it’s the price of confidence.",
    "A/B testing is the key to marketing improvement.",
    "Simplicity is the ultimate sophistication in software.",
    "The road to marketing success is paved with customer empathy.",
    "Clean code always wins in the long run.",
    "Build for maintainability, not just functionality.",
    "Marketing is telling the world you’re a rock star. Content marketing is showing them you are one.",
    "Documentation is for people, not machines.",
    "Great marketers listen more than they talk.",
    "Code is like humor. When you have to explain it, it’s bad.",
    "The best SEO strategies are ethical and long-term.",
    "Software development is 10% writing code and 90% understanding requirements.",
    "Marketing is really just about sharing your passion.",
    "Every line of code you write is a future maintenance problem you are creating today.",
    "Good marketers see customers as people, not targets.",
    "Your users are smarter than you think—treat them that way.",
    "A website’s SEO is never done—it’s always evolving.",
    "If you automate a mess, you get an automated mess.",
    "Marketing is the art of getting people to do what you want, without them noticing.",
    "Your first version is never your best version.",
    "Innovation comes from saying no to 1,000 things.",
    "Measure twice, code once.",
    "Marketing success is the sum of small, consistent actions.",
    "Code is read more than it is written.",
    "The customer is the ultimate product owner.",
    "Great software solves real problems, not imagined ones.",
    "SEO is patience in action, strategy in thought, and creativity in execution.",
];
